### ISSUE TITLE
upgrade to the latest version yields a ProgrammingError

### ISSUE THREAD

**Issue by schmitch** [divio/djangocms-picture#35]
Hello upgrading djangocms to the latest version yields a ProgrammingError in djangocms-picture:

```
 Applying djangocms_picture.0003_migrate_to_filer...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 181, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/djangocms_picture/migrations/0003_migrate_to_filer.py", line 25, in migrate_to_filer
    plugins.filter(pk=plugin.pk).update(picture=picture)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/db/models/query.py", line 563, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1048, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/schmitch/projects/envisia/websites/lapp/.venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: can't adapt type 'File'
```

I get that on multiple projects

**Comment by FinalAngel** [comment]
@schmitch that looks like migration problems. From what version are you upgrading? Does an upgrade to 2.0.0, 2.0.1 or 2.0.2 work for you? What django CMS Version are you using?

**Comment by schmitch** [comment]
I have django filer installed an the only upgrade that works is:
```

djangocms-file==1.0
djangocms-picture==0.2.0
djangocms-video==1.1.0
```

django filer is at: `django-filer==1.2.5`

**Comment by FinalAngel** [comment]
@schmitch thank you for the fast feedback. What version of django CMS is in use?

**Comment by schmitch** [comment]
well on that version it's `django-cms==3.4.1` video fails with a different error, but these errors are not too bad since I can run the previous version of these stuff, it's just sad that the migration fails, I guess I can somehow resolve the migration manually.

**Comment by FinalAngel** [comment]
@schmitch I'll try to debug it in the next couple of days and let you know if I can reproduce it.

**Comment by FinalAngel** [comment]
@schmitch I did the following inside a virtualenv:

```
pip install djangocms-installer
djangocms test_picture
cd test_picture
pip install django-cms==3.4.1
pip install djangocms-file==1.0
pip install djangocms-picture==0.2.0
pip install djangocms-video==1.1.0
```

then added file, picture and video to the ``INSTALLED_APPS``. Next:

```
python manage.py migrate
python manage.py runserver
```

And added a picture plugin with all fields filled (and other picture plugins without some data and so on). Next I went:

```
pip uninstall djangocms-picture
pip install djangocms-picture (which will install 2.0.3)
python manage.py migrate
```

and the output is:

```
⋊> ~/S/d/project_picture python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: project_picture, staticfiles, messages, djangocms_admin_style, sitemaps, sekizai, cmsplugin_filer_utils, treebeard
  Apply all migrations: cmsplugin_filer_file, cmsplugin_filer_image, sessions, djangocms_file, filer, admin, djangocms_column, djangocms_text_ckeditor, sites, auth, djangocms_video, cmsplugin_filer_folder, menus, contenttypes, djangocms_picture, djangocms_googlemap, djangocms_style, djangocms_link, cms, easy_thumbnails, djangocms_snippet
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying djangocms_picture.0003_migrate_to_filer... OK
  Applying djangocms_picture.0004_adapt_fields... OK
  Applying djangocms_picture.0005_reset_null_values... OK
  Applying djangocms_picture.0006_remove_null_values... OK
```

Installation works without any issues found. Here my full settings.py and pip freeze:
Settings.py: https://dpaste.de/Xr7V
Pip: https://dpaste.de/7UGU

Maybe that helps you to debug the project, I'm assuming some dependency is missing.

**Comment by FinalAngel** [comment]
@schmitch any feedback from your end?

**Comment by schmitch** [comment]
Sorry I actually didn't have time yesterday, also your dpaste's are offline.
I will take a look at the weekend.

**Comment by FinalAngel** [comment]
Yeah that goes offline after some time, here again at least the settings:

https://dpaste.de/kYqt

**Comment by schmitch** [comment]
Have no time currently to give more info, sorry :( but thanks for your help.

**Comment by FinalAngel** [comment]
thank you @schmitch anyways for the feedback
